Add Validation Blood Type
nadrzs/blood-nation-mobile pull request #3
Opened 2024-05-03 09:52 UTC by nadrzs

Adding validation for blood type form

2024-05-03 10:23 UTC, rickydbithealth requested changes

2024-05-03 10:23 UTC, rickydbithealth commented on blood_nation/lib/provider/setting_provider.dart
> +  bloodTypeValidator(String value) {
ini value bisa null ngak sih ?

2024-05-03 10:23 UTC, rickydbithealth commented on blood_nation/lib/pages/profile.dart
> +  String username = "johndoe";
kenapa harus pakai hardcoded data?

2024-05-06 01:47 UTC, nadrzs commented on blood_nation/lib/pages/profile.dart
> +  String username = "johndoe";
untuk sementara masih pakai hardcoded data dulu pak, karena nanti mau disambungkan ke API nya

2024-06-06 13:03 UTC, merged

2024-06-06 13:03 UTC, rickydbithealth approved these changes